/**
 * @file version_checker.cpp
 * @brief Version update checker implementation
 */

#include "version_checker.h"
#include "version.h"  // Auto-generated by CMake
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <iostream>
#include <thread>

#ifdef _WIN32
#include <windows.h>
#endif

namespace moonmic {

static const char* VERSION_URL = "https://raw.githubusercontent.com/AorsiniYT/moonmic/main/VERSION";
static const char* RELEASES_URL = "https://github.com/AorsiniYT/moonmic/releases";

VersionChecker::VersionChecker() {
}

VersionChecker::~VersionChecker() {
}

std::string VersionChecker::getCurrentVersion() {
    return MOONMIC_VERSION;  // From generated version.h
}

int VersionChecker::compareVersions(const std::string& v1, const std::string& v2) {
    std::istringstream ss1(v1), ss2(v2);
    int major1 = 0, minor1 = 0, patch1 = 0;
    int major2 = 0, minor2 = 0, patch2 = 0;
    char dot;
    
    ss1 >> major1 >> dot >> minor1 >> dot >> patch1;
    ss2 >> major2 >> dot >> minor2 >> dot >> patch2;
    
    if (major1 != major2) return (major1 > major2) ? 1 : -1;
    if (minor1 != minor2) return (minor1 > minor2) ? 1 : -1;
    if (patch1 != patch2) return (patch1 > patch2) ? 1 : -1;
    return 0;
}

std::string VersionChecker::fetchLatestVersion() {
    std::string result;
    
#ifdef _WIN32
    // Windows: use PowerShell to download
    char temp_file[MAX_PATH];
    GetTempPathA(MAX_PATH, temp_file);
    strcat_s(temp_file, "moonmic_version.txt");
    
    std::string cmd = "powershell -Command \"(New-Object Net.WebClient).DownloadFile('" + 
                     std::string(VERSION_URL) + "', '" + std::string(temp_file) + "')\" >nul 2>&1";
    
    if (system(cmd.c_str()) == 0) {
        std::ifstream file(temp_file);
        if (file.is_open()) {
            std::getline(file, result);
            file.close();
        }
        DeleteFileA(temp_file);
    }
#else
    // Linux: use curl
    const char* temp_file = "/tmp/moonmic_version.txt";
    std::string cmd = std::string("curl -s -o ") + temp_file + " " + VERSION_URL + " 2>/dev/null";
    
    if (system(cmd.c_str()) == 0) {
        std::ifstream file(temp_file);
        if (file.is_open()) {
            std::getline(file, result);
            file.close();
        }
        remove(temp_file);
    }
#endif
    
    // Trim whitespace
    if (!result.empty()) {
        size_t start = result.find_first_not_of(" \t\n\r");
        size_t end = result.find_last_not_of(" \t\n\r");
        if (start != std::string::npos && end != std::string::npos) {
            result = result.substr(start, end - start + 1);
        }
    }
    
    return result;
}

void VersionChecker::checkForUpdates(std::function<void(const VersionInfo&)> callback) {
    // Run check in background thread to avoid blocking UI
    std::thread([this, callback]() {
        VersionInfo info;
        info.current_version = getCurrentVersion();
        info.latest_version = fetchLatestVersion();
        info.download_url = RELEASES_URL;
        
        if (info.latest_version.empty()) {
            // Failed to fetch, assume no update
            info.update_available = false;
        } else {
            int cmp = compareVersions(info.latest_version, info.current_version);
            info.update_available = (cmp > 0);
        }
        
        callback(info);
    }).detach();
}

} // namespace moonmic
