
#pragma once

#define PLATFORM_SAMPLE_RATE 48000
#define PLATFORM_CHANNELS 1
#define PLATFORM_GRAIN_SIZE 480
#define PLATFORM_BITRATE 64000

#define PLATFORM_PCM_BUFFER_SIZE 4096
#define PLATFORM_OPUS_BUFFER_SIZE 4000

#define PLATFORM_NEEDS_PADDING 0
#define PLATFORM_PADDED_FRAME_SIZE 480

#define PLATFORM_NAME "Windows"
